apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app1
  template:
    metadata:
      labels:
        app: test-app1
    spec:
      serviceAccountName: test
      containers:
      - image: busybox
        name: test-app1
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 29; done;" ]
      initContainers:
      - name: job-done
        image: groundnuty/k8s-wait-for
        imagePullPolicy: IfNotPresent
        args:
          - "job"
          - "failed-job"
        
