apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
          - /bin/sh 
          - -c 
          - "exit 0"
      restartPolicy: Never