apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
          - /bin/sh 
          - -c 
          - "exit 1"
      restartPolicy: Never