apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
          - /bin/sh 
          - -c 
          - "exit 1"
      restartPolicy: Never